#!/bin/bash
# Author   : Anand Kulkarni
# Synopsis : Wrapper around the underlying oneDriveSync tool script.Automates the synchronization of the all requisite folders.

export srcFolder="/run/media/anand/Windows/os-common/repo"
export excludeFolderList="ExpanDrive|vmware" # Pipe seperate these items.
export logFileDir="/var/log/onedrive-sync"
export logFile="cloudsync.$(date +%d%m%Y_%H:%M:%S).log"

dirList=$(ls -l ${srcFolder}|grep ^d|awk '{print $9}'|egrep -v "${excludeFolderList}"|tr '\n' ' ')
for dir in ${dirList}
do
	oneDriveSync ${dir} 2&>1 | tee -a ${logFileDir}/${logFile}
done
