#!/bin/bash
# Author   : Anand Kulkarni
# Synopsis : Wrapper around the underlying oneDriveSync tool script.Automates the synchronization of the all requisite folders.

function displayUsage()
{
	echo -e "Usage : $0. The config file is a pipe seperated list of mandatory key and value pair seperated by comma."
	echo -e "The config file is expected in the path = $HOME/.config/rsynconf/cloudSync.conf"
}

if [ "$#" -ne 0 ]; then
	echo -e "Warning : The script does not need a paramter passed. Ignoring and continuing..."
fi

export inputConfigFile="$HOME/.config/rsynconf/cloudsync.conf"
if [ ! -f "${inputConfigFile}" ]; then
	echo -e "Fatal error : The mandatory config file required ${inputConfigFile} is not found.Exiting with error code 1..."
	exit 1
else
	echo -e "Found the ${inputConfigFile}.Proceeding to load it..."
fi

while IFS= read -r line
do
	varName=$(echo $line|awk -F"," '{print $1}')
	varValue=$(echo $line|awk -F"," '{print $2}')
	eval "export $varName=\"$varValue\""
done < ${inputConfigFile}

dirList=$(ls -l ${srcFolder}|grep ^d|awk '{print $9}'|egrep -v "${excludeFolderList}"|tr '\n' ' ')
for dir in ${dirList}
do
	oneDriveSync ${dir} 2>&1|tee -a ${logFileDir}/${logFile}
	exitCode="${PIPESTATUS[0]}" # The exit code of the first command i.e oneDriveSync script.
	if [ ${exitCode} -ne 0 ]; then
		echo -e "Error! The oneDriveSync script failed with non zero exit code = ${exitCode} during sync of folder ${dir}.Exiting the script with error code 1..."
		exit 1
	fi
done

# Run the automatic cleanup of logs area [ throw away anything older than 2 weeks ].
echo -e "cleaning up any files older than ${cleanUpDays}...."
find ${logFileDir} -type f -mtime ${cleanUpDays} | xargs rm -f

# Gracefully exit with success.
exit 0 
