#!/bin/bash
# List How many commit in repositories are due in ~/git/ area.

function showUsage()
{
  echo -e "Usage : dueCommits [git/bb] [all/due]."
  echo -e "repository argument can be either git or bb [bit bucket ]."
}

if [ "$#" -ne 2 ]; then
  showUsage
  exit 1
fi

repoType=$1

if [ "$repoType" != "git" -a "$repoType" != "bb" ]; then
  echo -e "repo argument passed is invalid.It must be git/bb. please check."
  showUsage
  exit 1
fi

repoDir="git"
if [ "$repoType" = "bb" ]; then
  repoDir="bitbucket"
fi

cwd=$PWD
gitDir=$HOME/$repoDir
dirList=$(ls -lrt $gitDir/ | grep -i ^d | egrep -v "external|archive" | awk '{print $9}')
countDueItems=0
for dirItem in $dirList
do
	cd $HOME/$repoDir/$dirItem
	dueCount=$(git status|egrep -i "Modified:|deleted:|new file:"|wc -l)
  unTrackedCount=$(git ls-files --others --exclude-standard|wc -l)
  dueCount=$((dueCount + unTrackedCount))
	if [ $dueCount -ge 1 ]; then
		echo -e "There are $dueCount commits due in : $dirItem"
		countDueItems=$((countDueItems+1))
	else
		if [ "$2" = "all" ]; then
			echo -e "$dirItem is clean."
		fi
	fi
done

if [ $countDueItems -eq 0 ]; then
	echo -e "All Clean!!"
fi
cd $cwd
