#!/bin/bash
# List How many commit in repositories are due in ~/git/ area.
cwd=$PWD
gitDir=$HOME/git
dirList=$(ls -lrt $gitDir/ | grep -i ^d | grep -v "external" | awk '{print $9}')
for dirItem in $dirList
do
	cd $HOME/git/$dirItem
	dueCount=$(git status|grep -i "Modified:"|wc -l)
	if [ $dueCount -ge 1 ]; then
		echo -e "There are $dueCount commits due in : $dirItem"
	else
		if [ "$1" = "all" ]; then
			echo -e "$dirItem is clean."
		fi
	fi
done
cd $cwd
