#!/bin/bash

if [ $# -ne 1 -a $# -ne 2 ]; then
  echo -e "Proper usage : gcm [ commit details. ] [optional : push to git y/n].";
  exit 1
else
  userComment=$1
  pushCommitToRepo=$(echo ${2:0:1}|tr '[:upper:]' '[:lower:]')
  if [ "$pushCommitToRepo" != "y" -a "$pushCommitToRepo" != "n" ]; then
    echo -e "The second parameter for pushing to git repo is must be either y/n.Please verify!!"
    exit 1
  fi
fi

whichMachine=$(uname -a | awk '{print $2}')
repoName=$(git config remote.origin.url | xargs basename | sed "s/.git//g")
echo -e "Processing the updates for repoName = $repoName"
if [ "$whichMachine" = "ubuntu" ]; then
  echo -e "Adding files to the git for commit."
  git add .
fi

# Generate git commit command with proper user and date time stamp details.
currDate=$(date +'%d/%m/%Y %H:%M:%S:%3N')
currTimeZone=$(timedatectl | grep -i "Time zone:"|awk -F":" '{print $2}'|sed "s/ //g")
userFullName=$(awk -v user="$USER" -F":" 'user==$1{print $5}' /etc/passwd | awk -F"," '{print $1}')

# Build the commit command from the date,timezone and user name.
fullComment=$(echo \"$userFullName "-" $currDate $currTimeZone "-" $userComment.\")
fullCommand=$(echo "git commit -m" $fullComment)

# Execute the command.
echo "Running the command --> $fullCommand"
eval $fullCommand
echo "Pushing the changes to git now"
read -p "Press any key to continue..." -n1 -s
if [ "$pushCommitToRepo" = "y" ]; then
  git push -v
else
  echo -e "Warning : Push to git skipped since not requested."
fi

exit 0
