#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo -e "Proper usage : gcm [ commit details. ]";
  exit 1
else
  userComment=$1
fi

# Generate git commit command with proper user and date time stamp details.
currDate=$(date +'%d/%m/%Y %H:%M:%S:%3N')
currTimeZone=$(timedatectl | grep -i "Time zone:"|awk -F":" '{print $2}'|sed "s/ //g")
userFullName=$(awk -v user="$USER" -F":" 'user==$1{print $5}' /etc/passwd | awk -F"," '{print $1}')

# Build the commit command from the date,timezone and user name.
fullComment=$(echo \"$userFullName "-" $currDate $currTimeZone "-" $userComment.\")
fullCommand=$(echo "git commit -m" $fullComment)

# Execute the command.
echo "Running the command --> $fullCommand"
eval $fullCommand
echo "Pushing the changes to git now"
read -p "Press any key to continue..." -n1 -s
git push -v

# sync the tiddlywiki updates to the fedora machine.
whichMachine=$(uname -a | awk '{print $2}')
if [ "$whichMachine" = "ubuntu" ]; then
  echo -e "Pushing the updates to the Fedora machine."
  ssh -t anand@ldnpsr2937.intranet.barcapint.com "updateTiddly"
fi

exit 0
