#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo -e "Proper usage : gcm [ commit details. ]";
  exit 1
fi

# Generate git commit command with proper user and date time stamp details.
currDate=$(date +'%d/%m/%Y %H:%M:%S:%3N')
currTimeZone=$(timedatectl | grep -i "Time zone:"|awk -F":" '{print $2}'|sed "s/ //g")
userFullName=$(awk -v user="$USER" -F":" 'user==$1{print $5}' /etc/passwd)
userComment=$1
fullComment=$(echo \"$currDate $currTimeZone "-" $userFullName "-" $userComment\")
fullCommand=$(echo "git commit -m" $fullComment)
echo "Running the command --> $fullCommand"
eval $fullCommand
echo "Pushing the changes to git now"
read -p "Press any key to continue..." -n1 -s
git push -v
exit 0
