#!/bin/bash

if [ $# -ne 1 ]; then
  binName=$(basename $0)
  echo -e "Usage   : $binName repositoryName (could be either in bitbucket/git in $HOME)."
  echo -e "Example : $binName fedoracustomsettings ( this folder is in $HOME/bitbucket)."
  exit 1
fi

# If no folder argument passed quit.
repoFolder=$1
if [ ! -d $HOME/git/$repoFolder -a ! -d $HOME/bitbucket/$repoFolder ]; then
  echo -e "The repository is not found in either git/bitbucket path.Please verify!!"
  exit 1
fi
repoType="git"
if [ -d $HOME/bitbucket/$repoFolder ]; then
  repoType="bitbucket"
fi

echo -e "Repository found in $HOME/$repoType folder."

# derive the type of repo based on below logic.
cwd=$(pwd)
cd $HOME/$repoType/$1;
echo -e "XXXXXXXXXXXXXXXXXXXXXXXXXX\nXX   git diff status:	XX\nXXXXXXXXXXXXXXXXXXXXXXXXXX\n"
git diff
echo -e "XXXXXXXXXXXXXXXXXXXXXXXXXX\nXX  git status:	XX\nXXXXXXXXXXXXXXXXXXXXXXXXXX\n"
git status
cd $cwd
exit 0
