#!/bin/bash

if [ $# -ne 3 ]; then
  echo -e "Usage : $0 [11/14/17] [fileName] [lib-switches]"
  echo -e "Ex:- $0 17 sample1.cpp \"-ltbb -lpthread\""
  echo -e "Ex:- $0 17 simple-sycl-app.cpp"
  exit 1
fi

buildType=$1
buildSrcFile=$2
buildLibs=$3

if [ "$buildType" != "11" -a "$buildType" != "14" -a "$buildType" != "17" ]; then
  echo  -e "Usage : Invalid first argument. It should be one of these. 11/14/17."
  exit 1
fi

objName=${buildSrcFile%.cpp}.out
executeCommand="g++ -std=c++$buildType -Wall $buildSrcFile -o $objName"
executeCommand="dpcpp -std=c++$buildType -Wall $buildSrcFile -o $objName $buildLibs"
echo -e "Running command : $executeCommand"
eval $executeCommand
