#!/bin/bash
echo -e "####################################################"
echo -e "#           MachineName|Machineuuid                #"
echo -e "####################################################"
virtualBoxPath="$HOME/.config/VirtualBox"
virtualBoxXml="VirtualBox.xml"
cat $virtualBoxPath/$virtualBoxXml|grep "MachineEntry"|awk -F"=" '{print $2,$3}'|awk -F"\"" '{print $4"|"$2}'|sed 's/\({\|}\)//g'
echo -e "####################################################"
exit 0
