#!/bin/bash
# Author : Anand Kulkarni
# Synopsis : one drive syncing tool custom written as wrapper around generic rsyncTool used to synchronize local folders to mounted one drive folder via ExpanDrive tool.
# First validate if the parameters passed are valid. We accept single parameter which is a folder name [ only selectable folder name from masterList]

function checkRootUser
{
  runUser=$(id|awk '{print $1}'|awk -F"=" '{print $2}')
  if [ "$runUser" != "0(root)" ] ; then
    echo -e "must be run by root."
    exit 1
  fi
}

function displayUsageHelp()
{
	echo -e "Usage : $0 [folder]. The folder can only be one of these values. [coderepo fedora win10 largeCppTestDataFiles vmware]."
}

function validateInputParameter()
{
	masterList="coderepo fedora win10 largeCppTestDataFiles vmware"
	returnStatus="false"
	for masterItem in ${masterList}
	do
		if [ "${1}" = "${masterItem}" ]; then
			returnStatus="true"
		fi
	done
	echo ${returnStatus}
}

# Check if the user running is root else kick out.
#checkRootUser

if [ "$#" -ne 1 ]; then
	displayUsageHelp
	exit 1
fi

# validate if the parameter passed is a valid one from masterList.
returnStatus=$(validateInputParameter $1)

if [ "${returnStatus}" != "true" ]; then
	echo -e "The input folder name is not reconginzed.Quitting the execution with error code 1.."
	echo -e "The masterList is = [coderepo fedora win10 largeCppTestDataFiles vmware]."
	exit 1
fi

# We now invoke the synchronization via rsyncTool.
echo -e "Proceeding to synchronize the folder ${1} to oneDrive.."
echo -e "Checking for status of the ExpanDrive mount..."
statusCount=$(findmnt|grep "ExpanDrive/onedrive"|grep "rw"|wc -l)
if [ $statusCount -eq 0 ]; then
	echo -e "Error!! Can not find the onedrive mount of ExpanDrive via findmnt tool.Exiting with error code 1..."
	exit 1
else
	echo -e "Successfully verified the onedrive mount of ExpanDrive.Proceding towards onedrive mount.."
fi

# Identify if the proper logFile name and redirect the log via pipe.
logFileFolder="/var/log/onedrive-sync"
logTimeStamp=$(date +"%m-%d-%Y.%r"|sed "s/:/./g"|sed "s/ /./g")
logFileName="${logFileFolder}/onedrivesync.${1}.${logTimeStamp}.log"
echo -e "Will be logging to the logFile = ${logFileName}"

# Execute the sync tool finally!
rsyncTool $HOME/tools/rsyncConfig/${1}.rsync.conf 2>&1 | tee -a ${logFileName} 
exit 0
