#!/bin/bash

function getTimeZone
{
  export var2="timedatectl | grep -i \"Time zone:\" | awk -F\":\" '{print $2}' | awk -F\" \" '{print $1}'|tr \"/\" \".\""
  export var2=$(eval $var2|awk -F":" '{ print $2 }' | awk -F" " '{print $1}')
  echo $var2
}

function getLogFileName
{
  export var1=$(date +'%d.%m.%Y_%H:%M:%S:%N')
  export var2=$(getTimeZone)
  appType=$1
  appName=$2
  logDir=$3
  logFileName=$(echo -e "$logDir/dnfupd.$appType.$appName.${var1}.${var2}.log" | sed "s/|/_/g"| sed "s/\./_/g"| sed "s/:/_/g")
  echo $logFileName
}

export logFileDir="/var/log/dnfupd"
export logFileName=$(getLogFileName $1 $2 $logFileDir)
dnfupd $1 $2 2>&1 | tee -a $logFileName
exit 0 
