#!/usr/bin/bash

repoType="dueCommits bb due"
pushType="b"

if [ "$#" -ne 1 ]; then
  echo "Usage : pushAll [g/b]. g->git, b->bitbucket."
  exit 1
else
  if [ "$1" != "g" -a "$1" != "b" ]; then
    echo "Usage : pushAll [g/b]. g->git, b->bitbucket."
    exit 1
  else
    if [ "$1" = "g" ]; then
      repoType="dueCommits git due"
      pushType="g"
    fi
  fi
fi

for repository in $(eval $repoType|awk -F":" '{print $2}'|sed "s/ //g"|tr "\n" " ")
do
  autocommit $pushType $repository 
done
