#!/usr/bin/bash

# verify only root can run this tool.
runUser=$(id|awk '{print $1}'|awk -F"=" '{print $2}')
if [ "$runUser" != "0(root)" ] ; then
  echo -e "must be run by root."
  exit 1
fi

# Attempt to suspend immediately. First trigger wifi turn off and then run systemctl suspend -i.
nmcli radio wifi off
systemctl suspend -i
exit 0
