#!/bin/bash
# Invoke an oracle virtual machine using its machineId. This tools depends on listovm script.
# Author : Anand Kulkarni
# Date : 10/09/2022
# Synopsis : The script invokes an oracle virtual machine by taking it vm name.
# The machine name matching is via case insensitive grep and pick the first match(via head -1)
if [ $# -ne 1 ]; then
  echo -e "No machine id/name passed. Exiting with error."
  echo -e "Sample usage : $0 mint21\nThis will look for a oracle virtual machine named mint21.vbox and corrosponding uuid for invocation."
  exit 1
fi

machineName=$1
oracleVmMachineDetails=$($HOME/tools/listovm|grep -i $machineName|head -1)
doesMachineExist=$(echo $oracleVmMachineDetails|grep -v ^$|wc -l|sed -e "s/1/y/g;s/0/n/g")

if [ "$doesMachineExist" = "n" ]; then
  echo -e "The given machine $machineName.vbox does not exist.Please check the oracle vm settings!!"
  exit 1
else
  echo -e "The nearest/first machine matching given param $1 is :->" $(echo $oracleVmMachineDetails|awk -F"|" '{print $1}')
fi

# Invoke the machine here.
oracleVmManagerBin="/usr/lib/virtualbox/VirtualBoxVM"
machineUUID=$(echo $oracleVmMachineDetails|awk -F"|" '{print $2}')
invokeCommand="nohup $oracleVmManagerBin --comment $machineName --startvm $machineUUID --no-startvm-errormsgbox &"
echo -e $(date) ":-> $invokeCommand" >> /var/log/oraclevm.machines.startstop.log
eval $invokeCommand
exit 0
