#!/bin/bash

function isNumber()
{
    numPattern='^[0-9]+$'
    if ! [[ $1 =~ $numPattern ]] ; then
        echo -e "no"
    else
        echo -e "yes"
    fi
}

# Validation of port number passed as argument.
if [ "$#" -ne 1 ]; then
    echo -e "Usage : runqat [port]"
    exit 1
else
    isPortNumeric=$(isNumber $1)
    if [ "$isPortNumeric" = "no" ]; then
        echo -e "error: Not a number argument! Exiting with error."
        exit 1
    fi
    if [ $1 -le 1023 -o $1 -ge 65536 ]; then
        echo -e "Please pass a port greater than 1023(2^10-1) and less than 65536(2^16-1)."
        exit 1
    fi
fi

# Main start of execution.
cpuCores=$(lscpu|grep ^$"CPU(s):"|awk -F":" '{print $2}'|sed "s/  //g")
export QHOME=~/coding/q
rlwrap $QHOME/l32/q -p $1 -s ${cpuCores}
