#!/bin/bash

function checkRootUser
{
  runUser=$(id|awk '{print $1}'|awk -F"=" '{print $2}')
  if [ "$runUser" != "0(root)" ] ; then
    echo -e "must be run by root."
    exit 1
  fi
}
checkRootUser
logFileFolder="/var/log/vmware-kernel-compile"
if [ ! -d ${logFileFolder} ]; then
  mkdir -p ${logFileFolder}
fi
logFileName=$(date +%d%m%Y)
logFileName="vmware.rebuild.${logFileName}.log"
vmware-modconfig --console --install-all 2>&1 | tee ${logFileFolder}/${logFileName}
